#!/usr/bin/env node
// Concatenates src/*.js into the three shipped builds. No dependencies.
//   node build.js
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const EXT = path.join(ROOT, 'extension');

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;
const CHECK_ONLY = process.argv.includes('--check');

const CORE_FILES = [
  '00-css.js', '10-i18n.js', '11-locales-extra.js', '20-dom.js', '30-api.js',
  '40-store.js', '50-feed.js', '60-swipe.js', '70-review.js', '80-app.js',
];

const read = (f) => fs.readFileSync(path.join(SRC, f), 'utf8').replace(/\s+$/, '');
const core = CORE_FILES.map(read).join('\n\n');
const launcher = read('90-launcher.js');

const banner = (what) => `/*!
 * @license MIT
 * FolioPause v${VERSION} — ${what}
 * Card-based review for photos.google.com. Swipe left to mark, right to keep;
 * nothing is deleted until you review and confirm, and deleting only moves
 * photos to Google's Trash (recoverable for 60 days).
 *
 * Runs locally with no third-party server or analytics. It talks only to the
 * signed-in Google Photos session and Google-hosted media endpoints.
 * ${pkg.license} licensed. See LICENSE and THIRD_PARTY_NOTICES.md.
 * Generated by build.js — edit files in src/, not this one.
 */`;

const wrap = (bodyTail, testMode) => `(function () {
  'use strict';
  if (window.__gpSwipe) { window.__gpSwipe.open(); return; }
  const APP_VERSION = ${JSON.stringify(VERSION)};
  const GP_TEST_MODE = ${testMode === true ? 'true' : 'false'};

${core}

${bodyTail}
})();
`;

// 1. console build — paste into DevTools, opens straight away
const consoleBuild = `${banner('console build')}
${wrap('  app.show();', false)}`;

// 2. extension content script (MAIN world) — shows the launcher, waits
const contentBuild = `${banner('extension content script')}
${wrap(launcher.split('\n').map((l) => (l ? '  ' + l : l)).join('\n'), false)}`;

// 3. userscript (optional, for Tampermonkey users)
const userscript = `// ==UserScript==
// @name         FolioPause — Review Before Trash
// @namespace    ${pkg.homepage}
// @version      ${VERSION}
// @description  ${pkg.description}
// @author       ${pkg.author}
// @match        https://photos.google.com/*
// @run-at       document-idle
// @grant        none
// @noframes
// ==/UserScript==
${banner('userscript build')}
${wrap(launcher.split('\n').map((l) => (l ? '  ' + l : l)).join('\n'), false)}`;

// Test-only white-box bundle. Its capability is an immutable closure constant,
// never a page-controlled production flag.
const testBuild = `${banner('test harness build')}
${wrap('  app.show();', true)}`;

fs.mkdirSync(DIST, { recursive: true });
fs.mkdirSync(EXT, { recursive: true });
fs.mkdirSync(path.join(ROOT, 'test', 'generated'), { recursive: true });

const outputs = [
  [path.join(DIST, 'foliopause-console.js'), consoleBuild],
  [path.join(DIST, 'foliopause.user.js'), userscript],
  [path.join(EXT, 'foliopause-content.js'), contentBuild],
  [path.join(ROOT, 'test', 'generated', 'gpswipe-test.js'), testBuild],
];

// Keep each distributable directory self-contained for unpacked installs and
// source archives.
for (const notice of ['LICENSE', 'THIRD_PARTY_NOTICES.md']) {
  const source = path.join(ROOT, notice);
  if (!fs.existsSync(source)) continue;
  const content = fs.readFileSync(source, 'utf8').replace(/\s*$/, '\n');
  outputs.push([path.join(DIST, notice), content], [path.join(EXT, notice), content]);
}

// keep the extension manifest version in step with package.json
const manifestPath = path.join(EXT, 'manifest.json');
if (fs.existsSync(manifestPath)) {
  const m = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  m.version = VERSION;
  outputs.push([manifestPath, JSON.stringify(m, null, 2) + '\n']);
}

const stale = [];
for (const [file, content] of outputs) {
  // The white-box test bundle is intentionally ignored and generated on
  // demand. Everything users install/copy must already match source control.
  if (CHECK_ONLY) {
    if (file.indexOf(path.join('test', 'generated')) !== -1) continue;
    let actual = null;
    try { actual = fs.readFileSync(file, 'utf8'); } catch (e) { /* missing = stale */ }
    if (actual !== content) stale.push(path.relative(ROOT, file));
    continue;
  }
  fs.writeFileSync(file, content);
  console.log('wrote ' + path.relative(ROOT, file) + '  (' + (content.length / 1024).toFixed(1) + ' KB)');
}

if (CHECK_ONLY) {
  if (stale.length) {
    console.error('stale generated artifact(s): ' + stale.join(', ') + '\nRun npm run build and commit the results.');
    process.exitCode = 1;
  } else {
    console.log('shipped artifacts match src/ and package metadata');
  }
}
